### ISSUE TITLE
Openbabel integration failed

### ISSUE THREAD

**Issue by Crispae** [MolecularAI/DockStream#11]
I am trying to implement Dockstream with the vina backend, an exception is raised with openBabel executable.

Traceback (most recent call last):
File "DockStream/target_preparator.py", line 130, in
prep = AutodockVinaTargetPreparator(conf=config, target=input_pdb_path, run_number=run_number)
File "C:\Users\Y-8874903-E.ESTUDIANT\OneDrive - URV\Escritorio\PLIP interaction\DockStream\dockstream\core\AutodockVina\AutodockVina_target_preparator.py", line 56, in init
raise TargetPreparationFailed("Cannot initialize OpenBabel external library, which should be part of the environment - abort.")
dockstream.utils.dockstream_exceptions.TargetPreparationFailed: Cannot initialize OpenBabel external library, which should be part of the environment - abort.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "DockStream/target_preparator.py", line 139, in
raise TargetPreparationFailed() from e
dockstream.utils.dockstream_exceptions.TargetPreparationFailed

Follow all necessary steps mentioned in docs.

**Comment by YiYuDL** [comment]
I have the same problem when using Vina.
