### ISSUE TITLE
No module named 'ccdc'

### ISSUE THREAD

**Issue by Evert-Homan** [MolecularAI/DockStream#9]
I believe I successfully installed the normal (not Full) DockStream package as per your instructions on the github site, and then  tried to run the unit test, but this fails with a complaint regarding the ccdc module missing (see below). But I want to use Glide so wouldn’t need (nor have) ccdc. I am doing this on Ubuntu 18.04.

Dockstream/python ./unit_tests.py 
Traceback (most recent call last):
  File "./unit_tests.py", line 10, in <module>
    from tests.Gold import *
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Gold/__init__.py", line 1, in <module>
    from tests.Gold.test_Gold_target_preparation import *
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Gold/test_Gold_target_preparation.py", line 11, in <module>
    from dockstream.core.Gold.Gold_target_preparator import GoldTargetPreparator
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Gold/Gold_target_preparator.py", line 3, in <module>
    import ccdc
ModuleNotFoundError: No module named 'ccdc'

**Comment by CMargreitter** [comment]
Hi Evert,

Thanks for using our tools. This is indeed not something that should happen if you are using the normal environment.
I see that you are trying to execute the unit tests and for GOLD ones, CCDC is required (there should be a safeguard in place, though).

Can you try to comment out this line in the unit_tests.py: from tests.Gold import *

As for how to execute Glide, that depends on your installation. Do you use a module? Or do you call it from the command-line?

Best,
Christian

**Comment by Evert-Homan** [comment]
I made the unit_test.py file look like this but I get a lot of error messages when running it:

#!/usr/bin/env python
#  coding=utf-8

import unittest
# from tests import *
# from tests.ligand import *
# from tests.AutodockVina import *
# from tests.RDkit import *
# from tests.rDock import *
# from tests.Gold import *
from tests.Schrodinger import *
# from tests.OpenEye_Hybrid import *
# from tests.Corina import *
# from tests.TautEnum import *

if __name__ == '__main__':
    unittest.main()

This produces a lot of garbage but maybe it looks OK? 

EEEEEEE[17:13:04] SMILES Parse Error: syntax error while parsing: CXXC
[17:13:04] SMILES Parse Error: Failed parsing SMILES 'CXXC' for input: 'CXXC'
EEEEEEEEEEEEEE.
======================================================================
ERROR: test_aligning_discard (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 354, in test_aligning_discard
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_aligning_keep (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 313, in test_aligning_keep
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 40, in test_coordinate_generation
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation_AWS (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 67, in test_coordinate_generation_AWS
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation_parallelized (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 112, in test_coordinate_generation_parallelized
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation_with_Ligprep_stereo (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 231, in test_coordinate_generation_with_Ligprep_stereo
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation_with_Ligprep_stereo_command_line_parameters (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 255, in test_coordinate_generation_with_Ligprep_stereo_command_line_parameters
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation_with_RDkit_stereo (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 280, in test_coordinate_generation_with_RDkit_stereo
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation_with_epik (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 139, in test_coordinate_generation_with_epik
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation_with_epik_and_filtering (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 189, in test_coordinate_generation_with_epik_and_filtering
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_coordinate_generation_with_epik_parameters_set (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 166, in test_coordinate_generation_with_epik_parameters_set
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_failed_generation (tests.Schrodinger.test_ligprep_ligand_preparation.Test_Ligprep_ligand_preparation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_ligprep_ligand_preparation.py", line 94, in test_failed_generation
    prep = LigprepLigandPreparator(ligands=lig_parser.get_ligands(), **conf)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

======================================================================
ERROR: test_Glide_docking_and_result_parsing (tests.Schrodinger.test_Schrodinger_backend.Test_Schrodinger_backend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_Schrodinger_backend.py", line 147, in test_Glide_docking_and_result_parsing
    docker = Glide(**run_parameters)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Glide_docker.py", line 203, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

======================================================================
ERROR: test_Glide_docking_and_result_parsing_parallelized (tests.Schrodinger.test_Schrodinger_backend.Test_Schrodinger_backend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_Schrodinger_backend.py", line 207, in test_Glide_docking_and_result_parsing_parallelized
    docker = Glide(**run_parameters)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Glide_docker.py", line 203, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

======================================================================
ERROR: test_Glide_docking_and_result_parsing_parallelized_constraints (tests.Schrodinger.test_Schrodinger_backend.Test_Schrodinger_backend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_Schrodinger_backend.py", line 364, in test_Glide_docking_and_result_parsing_parallelized_constraints
    docker = Glide(**run_parameters)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Glide_docker.py", line 203, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

======================================================================
ERROR: test_Glide_docking_and_result_parsing_parallelized_enumerated_ligands (tests.Schrodinger.test_Schrodinger_backend.Test_Schrodinger_backend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_Schrodinger_backend.py", line 294, in test_Glide_docking_and_result_parsing_parallelized_enumerated_ligands
    docker = Glide(**run_parameters)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Glide_docker.py", line 203, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

======================================================================
ERROR: test_Glide_docking_and_result_parsing_parallelized_subjob_restriction (tests.Schrodinger.test_Schrodinger_backend.Test_Schrodinger_backend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_Schrodinger_backend.py", line 251, in test_Glide_docking_and_result_parsing_parallelized_subjob_restriction
    docker = Glide(**run_parameters)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Glide_docker.py", line 203, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

======================================================================
ERROR: test_Glide_docking_with_token_guard (tests.Schrodinger.test_Schrodinger_backend.Test_Schrodinger_backend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_Schrodinger_backend.py", line 416, in test_Glide_docking_with_token_guard
    docker = Glide(**run_parameters)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Glide_docker.py", line 203, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

======================================================================
ERROR: test_Glide_input_file_preparation_constraint (tests.Schrodinger.test_Schrodinger_backend.Test_Schrodinger_backend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_Schrodinger_backend.py", line 129, in test_Glide_input_file_preparation_constraint
    docker = Glide(**run_parameters)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Glide_docker.py", line 203, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

======================================================================
ERROR: test_Glide_input_file_preparation_simple (tests.Schrodinger.test_Schrodinger_backend.Test_Schrodinger_backend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_Schrodinger_backend.py", line 98, in test_Glide_input_file_preparation_simple
    docker = Glide(**run_parameters)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/Glide_docker.py", line 203, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

======================================================================
ERROR: test_token_guard_with_execution (tests.Schrodinger.test_token_guard.Test_Schrodinger_token_guard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/evehom/Projects/CompChem/DockStream/tests/Schrodinger/test_token_guard.py", line 37, in test_token_guard_with_execution
    self.assertTrue(token_guard.guard())
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/license_token_guard.py", line 101, in guard
    licadmin_output = self._get_licstat_output()
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/core/Schrodinger/license_token_guard.py", line 77, in _get_licstat_output
    result = self._executor.execute(command=_EE.LICADMIN, arguments=[_EE.LICADMIN_STAT], check=True)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/utils/execute_external/execute.py", line 57, in execute
    location=location)
  File "/media/data/evehom/Projects/CompChem/DockStream/dockstream/utils/execute_external/execute.py", line 38, in execute
    shell=True)
  File "/opt/anaconda3/envs/DockStream/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['module load schrodinger/2019-4 && licadmin STAT']' returned non-zero exit status 127.

----------------------------------------------------------------------
Ran 22 tests in 1.395s

FAILED (errors=21)

**Comment by CMargreitter** [comment]
Hi Evert,

Yes, that's to be expected since Ligprep and Glide cannot be initialize. That brings me back to the question how you load them when you call them normally from the command-line: Are you using a module (then we need to set "prefix_execution") or do you set $SCHRODINGER manually and call a path (then exporting $SCHRODINGER in the header and setting the "binary_path" is necessary)?

**Comment by Evert-Homan** [comment]
Hi,

I usually just click on the Maestro icon to start the Schrodinger software :-). But otherwise I set $SCHRODINGER manually to where the suite is installed through my .bashrc (export SCHRODINGER=/opt/schrodinger/2021-4). To be honest I am a novice when it comes to Python so how woudl I specify this in the unit_test.py file?

Thx/Evert
